name: Checkmarx One Scan
on:
  push:
    branches:
      - main
      
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: WebGoatcopy
          cx_tenant: ast_abdul_ansari
          base_uri: https://eu.ast.checkmarx.net
          cx_client_id: Gitactions_P 
          cx_client_secret: KbqZQbBi7bPDyI0vtLLkv58xysN2wLrc 
